// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfAZfS_6Evi0D8D1DiF0sWB3b0KqUs9S0',
    appId: '1:242283339931:web:a55993b2964e7ccd18a63e',
    messagingSenderId: '242283339931',
    projectId: 'multi-branch-stock-manager',
    authDomain: 'multi-branch-stock-manager.firebaseapp.com',
    storageBucket: 'multi-branch-stock-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD83CC9lCiaSEszgFM325efcuMXZAGc8QE',
    appId: '1:242283339931:android:f21fee0bac6f68e718a63e',
    messagingSenderId: '242283339931',
    projectId: 'multi-branch-stock-manager',
    storageBucket: 'multi-branch-stock-manager.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfAZfS_6Evi0D8D1DiF0sWB3b0KqUs9S0',
    appId: '1:242283339931:web:e7c6f420d07593cd18a63e',
    messagingSenderId: '242283339931',
    projectId: 'multi-branch-stock-manager',
    authDomain: 'multi-branch-stock-manager.firebaseapp.com',
    storageBucket: 'multi-branch-stock-manager.firebasestorage.app',
  );
}
